language: cpp

compiler:
  - gcc
  - clang
  
branches:
except:
- /^safer.*$/ 

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
# g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
# clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  #libstdc++-4.8 is needed by Clang to build too
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq g++-4.8 libstdc++-4.8-dev; fi
#  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi
  # boost is needed for unit tests. boost is not pre-installed in the Travis CI.
  - sudo apt-get install -qq libboost-dev
  - sudo apt-get install -qq libboost-test-dev

script:
  - $CXX --version
  - cd devscan && cmake . && make
  - cd client/test && cmake . && make
  - ./devicemonitor.test


env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "MJcCz4t+WTjNT5dFPJx0+gTEhhzLW3IsjdTGHQoTH39a/wrIdcskUgpZQE6PCkoQz0tFTVixeYzCbmX2jCb7mbviX3sClEgP0ghogsoxo/hVPmhU5Zxg6xmEwwIDvUbztMwcM/pb/vNt4TgXxI9L6EMfsvCwR38w+wng4uMQZ3c="

addons:
  coverity_scan:
    project:
      name: "HBM/devscan"
      description: "Build submitted via Travis CI"
    notification_email: stefan.waldschmidt@hbm.com
    build_command_prepend: "cd devscan; cmake ."
    build_command:  "make"
    branch_pattern: coverity_scan
